### ISSUE TITLE
Allow passing and array of names and colors to create multiple spinners at once

### ISSUE THREAD

**Issue by hacknug** [aniftyco/tailwindcss-spinner#2]
Instead of requiring the plugin multiple times, I think it would be a good idea being able to pass an array of objects to create multiple spinners at once.

**Comment by joshmanders** [comment]
With your recent PR what do you think we should do to support this?

**Comment by joshmanders** [comment]
What do you think about accepting an object or an array, if an object then it only makes one spinner with those values,, but if you accept an array, it makes as many spinners as that array has, and each item in the array is a config object for the spinner.

```js
[{
  name: 'spinner-blue',
  color: 'blue',
}, {
  name: 'spinner-red',
  color: 'red'
}]
```

We'll merge the objects with the defaults so that you don't have to repeat yourself.

**Comment by hacknug** [comment]
Sounds good to me!

**Comment by gmask** [comment]
Any word on this? I find myself needing at least 3 different spinners of various sizes and colors for different parts of the app, currently using FontAwesome until this is implemented.

**Comment by joshmanders** [comment]
@gmask been pretty busy lately and haven't had time to give this library any love. I am fully open to PR's if you want to help out.

**Comment by hacknug** [comment]
Same here. Ideally we should be able to pass in variants too. So maybe that array should be part of a config object like this:

```js
{
	spinners: [{
		name: 'spinner-blue',
		color: 'blue',
	}, {
		name: 'spinner-red',
		color: 'red'
	}],
	variants: ['responsive'],
}
```

@gmask anything else you're missing?

**Comment by gmask** [comment]
@hacknug It'd be cool to have a `speed` option as well that would control the animation property: `animation: spinAround 500ms infinite linear', just keep it in milliseconds so it could be set like `speed: 1000ms`,

@joshmanders I'd love to help but unfortunately I am not familiar enough with tailwind plugins or the tailwind source to produce a pull request at this time.

**Comment by hacknug** [comment]
Okay! Will try to do it this weekend then ;)

**Comment by hacknug** [comment]
I think you already did. If not, don't worry, I'll be opening a PR anyway so we can review and discuss the new config 👍

**Comment by joshmanders** [comment]
Yep, looks like I did.

**Comment by hacknug** [comment]
I was thinking it might be a good idea to write a couple tests to check everything works fine generating CSS for the default and a custom multi-spinner config. Do you guys have more experience with this than I do? haha

Custom `speed` has been implemented and I'll try to learn more about testing and jest before doing the multi-spinner refactor (just to make sure everything is fool-proof from now on on this plugin and all of my other ones).

**Comment by hacknug** [comment]
They say _better late than never_ so I'll be opening a PR in a couple hours adding support for Tailwind v1.x, tests, and solving all of the issues we discussed here.

Just to make it easier on me, I've rebuilt it using the same abstractions and helper functions I've used for all of my plugins so it should be easier to maintain down the road (at least if I have to do it, not sure about other tho haha).

```js
theme: {
  spinner: {
    default: {
      color: '#dae1e7',
      size: '1em',
      border: '2px',
      speed: '500ms',
    },
    md: {
      color: 'currentColor',
      size: '2em',
      border: '2px',
      speed: '500ms',
    },
  },
},
```

```css
.spinner {
  position: relative;
  color: transparent !important;
  pointer-events: none;
}

.spinner::after {
  content: '';
  position: absolute !important;
  top: calc(50% - (1em / 2));
  left: calc(50% - (1em / 2));
  display: block;
  width: 1em;
  height: 1em;
  border: 2px solid #dae1e7;
  border-radius: 9999px;
  border-right-color: transparent;
  border-top-color: transparent;
  animation: spinAround 500ms infinite linear;
}

.spinner-md {
  position: relative;
  color: transparent !important;
  pointer-events: none;
}

.spinner-md::after {
  content: '';
  position: absolute !important;
  top: calc(50% - (2em / 2));
  left: calc(50% - (2em / 2));
  display: block;
  width: 2em;
  height: 2em;
  border: 2px solid currentColor;
  border-radius: 9999px;
  border-right-color: transparent;
  border-top-color: transparent;
  animation: spinAround 500ms infinite linear;
}

@keyframes spinAround {
  from { transform: rotate(0deg); }
  to { transform: rotate(359deg); }
}
```
